### ISSUE TITLE
sqlite error after starting

### ISSUE THREAD

**Issue by Bering-Sea** [derektgardner/AboveHartland#8]
When I run the program i get an sqlite error?

Traceback (most recent call last):
  File "tracker.py", line 30, in <module>
    conn = sqlite3.connect('aircraftCount.db')
sqlite3.OperationalError: unable to open database file

I am running a pi 3b with piaware.

**Comment by Bering-Sea** [comment]
I went back and used your previous version with pickle and it seems to be working fine. I googled a little bit about sqlite3 and decided that I don't want to mess with it and will close this. Thanks!

**Comment by derektgardner** [comment]
Interesting. I haven't been able to recreate this issue. Could it be a permissions issue on your filesystem?

Did you try restarting the pi? If so did you get the same result? 

Glad the pickle solution is working for you! I ran that for quite a while with no issues.

**Comment by Bering-Sea** [comment]
I reinstalled it becuase of a SD card issue and i now get this error?


  File "tracker.py", line 31, in <module>
    pickle_out = open("seenAircraft.pickle", "wb")
PermissionError: [Errno 13] Permission denied: 'seenAircraft.pickle'

**Comment by Bering-Sea** [comment]
well after some deep searches into the web I think i fixed the pickle and the sqlite 3 problem i am having.

I put the full file path and they both work now, but ill stick with pickle for now. 

Thanks

if os.path.isfile('/home/pi/seenAircraft.pickle'):
    print('seenAircraft dictionary is present')
    pickle_in = open("seenAircraft.pickle", "rb")
    aircraftCount = pickle.load(pickle_in)
else:
    print('nope')
    aircraftCount = {}
    pickle_out = open("/home/pi/seenAircraft.pickle", "wb")
    pickle.dump(aircraftCount, pickle_out)
